import json

data = [
    {
        "page_number": 3,
        "id": "disease_1",
        "content": {
            "disease_name": "BACTERIAL CANKER",
            "causative_agent": "Clavibacter michiganensis subsp. michiganensis",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) SYMPTOMS ON COTYLEDONS. 2) YOUNG LEAVES AS SMALL CREAM-COLOURED SPOTS. 3) SPOTS OF DIAMETER 22mm, BUT THIS IS NOT COMMON. 4) PLANTS GROW POORLY AND WILT. 5) YOUNG PLANTS MAY WILT AND DIE, DEPENDING UPON LEVEL OF INFECTION. 6) WILTING CAN OCCUR ON THE ONE SIDE OF THE LEAFLETS, CALLED UNILATERAL WILTING. 7) PLANTS MAY WILT TEMPORARILY IN WARM PART OF THE DAY AND THEN RECOVER. 8) LEAVES MAY HAVE GREENISH-GREY REGIONS OF COLLAPSED TISSUE. 9) LEAFLETS OF THE OLDEST LEAVES CURL, YELLOW, WILT, AND FINALLY TURN BROWN AND COLLAPSE. 10) SECONDARY INFECTION- NECROSIS BEGINNING AT THE MARGINS AND SPREADING INWARDS (FIRING). 11) ADVENTITIOUS ROOTS MAY DEVELOP. 12) YELLOW TO BROWN CANKERS OCCASIONALLY FORM LONGITUDINALLY ON STEMS AND PETIOLES. 13) SECONDARY FRUIT SYMPTOMS IN THE FIELD BEGIN AS SMALL, WHITE SPOTS WHICH EXPAND AND BECOME LIGHT-BROWN AND RAISED IN THE CENTER (BIRD'S-EYE SPOTS). 14) IN PROTECTED CULTURE, FRUIT CAN EXHIBIT A NETTED APPEARANCE. 15) LIGHT AND LATER DARK STREAKS MAY DEVELOP ON STEMS. 16) BRANCHES BREAK OFF EASILY. 17) LESIONS ARE DARK BROWN TO ALMOST BLACK. 18) ESPECIALLY NEAR CALYX.",
            "conditions_for_the_disease": "1) INFECTION GENERALLY OCCURS THROUGH WOUNDS IN PLANT TISSUE. 2) CAN ALSO OCCUR THROUGH STOMATA, HYDATHODES OR ROOTS. 3) SECONDARY SPREAD OCCURS FROM SPLASHING WATER, CONTAMINATED EQUIPMENT, TOOLS AND ACTIVITIES. 4) MODERATE TEMPERATURES (18-24°C) AND GREATER THAN 80% RELATIVE HUMIDITY FAVOR DISEASE DEVELOPMENT. 5) LOW LIGHT INTENSITY AND HIGH NUTRIENT LEVELS (ESPECIALLY NITROGEN), ALSO ENHANCE DISEASE DEVELOPMENT. 6) SYMPTOMS TEND TO BE MORE SEVERE IN SANDY SOILS.",
            "cure__control_and_management": "1) PLANTING CLEAN TRANSPLANTS IS THE MOST IMPORTANT CONTROL MEASURE. 2) SOW ONLY SEED THAT HAS BEEN TESTED AND CERTIFIED FREE OF PATHOGEN. 3) IN SEEDLING PRODUCTION, USE ONLY STEAM-STERILIZED GROWING MEDIA AND HARD PLASTIC TRAYS. 4) INSPECT SEEDLINGS REGULARLY. 5) AVOID PLANTING TOMATOES IN FIELDS WHERE BACTERIA WAS DETECTED WITHIN LAST 5 YEARS OR WHERE SOLANACEOUS CROPS HAVE BEEN GROWN PAST 3 YEARS. 6) SANITIZE EQUIPMENT BETWEEN FIELDS. 7) USE NEW STAKES AND TWINE. 8) OVERHEAD IRRIGATION SHOULD BE AVOIDED; DRIP IRRIGATION IS PREFERRED. 9) AVOID ACTIVITY IN THE FIELD WHEN PLANTS ARE WET. 10) AT THE END OF THE SEASON, CROP DEBRIS SHOULD BE THOROUGHLY PLOWED UNDER."
        }
    },
    {
        "page_number": 4,
        "id": "disease_2",
        "content": {
            "disease_name": "BACTERIAL SPECK",
            "causative_agent": "Pseudomonas syringae pv. tomato (Two races, 0 and 1, have been identified.)",
            "distribution": "RACE O-WORLDWIDE. RACE 1- BULGARIA, CANADA, ITALY, SERBIA AND UNITED STATES",
            "signs_and_symptoms": "1) THIS BACTERIUM CAN ATTACK THE LEAVES, STEMS, PETIOLES, FLOWERS AND FRUIT. 2) FOLIAR SYMPTOMS APPEAR AS DARK-BROWN TO BLACK SPOTS, OFTEN SURROUNDED BY A YELLOW HALO. 3) TISSUE ADJACENT TO THE LESIONS IS INITIALLY YELLOW. 4) LESIONS CAN BE CIRCULAR TO ANGULAR IN SHAPE AND MAY HAVE A GREASY APPEARANCE. 5) LESIONS CAN ALSO FORM ON LEAF MARGINS WHERE GUTTATION DROPLETS COLLECT. 6) LARGE AREAS OF LEAF TISSUE BECOME NECROTIC AS LESIONS COALESCE. 7) OVAL TO ELONGATED BLACK LESIONS MAY OCCUR ON STEMS AND PETIOLES. 8) FRUIT LESIONS ARE SUPERFICIAL. 9) SELDOM PENETRATING MORE THAN A FEW CELLS DEEP. 10) SMALL (1 MM) AND SPECK-LIKE, BUT OCCASIONALLY CAN BE LARGER AND SUNKEN. 11) CAUSE RAISED BLACK SPOTS ON MATURE FRUIT.",
            "conditions_for_the_disease": "1) THE BACTERIA SURVIVE IN SOIL, IN DEBRIS FROM DISEASED PLANTS, AND ON SEEDS. 2) DISEASE DEVELOPMENT IS FAVORED BY COOL TO MODERATE TEMPERATURES (13-25°C) AND RAINFALL OR SPRINKLER IRRIGATION. 3) DISEASE PROGRESS IS STOPPED DURING HOT WEATHER. 4) ONE DAY OF CONTINUOUS LEAF WETNESS IS REQUIRED FOR DISEASE TO DEVELOP. 5) THIS BACTERIUM CAN SURVIVE ON MANY CROPS AND WEEDS. 6) SEED TRANSMISSION IS USUALLY OF MINOR IMPORTANCE.",
            "cure__control_and_management": "1) DELAY PLANTING IN SPRING TO AVOID EXPOSING TOMATOES TO COOL, WET CONDITIONS. 2) COPPER SPRAYS APPLIED EARLY AS PROTECTANTS CAN REDUCE DISEASE INCIDENCE. 3) AVOID SPRINKLER IRRIGATION. 4) FURROW OR DRIP IRRIGATION SHOULD BE USED WHEN POSSIBLE. 5) PLANT RACE O-RESISTANT VARIETIES THAT CARRY THE PTO GENE. 6) NO RACE 1 RESISTANCE CURRENTLY DEPLOYED. 7) DO NOT PLANT TOMATOES IN A FIELD PREVIOUSLY PLANTED TO TOMATOES THAT DEVELOPED THE DISEASE; ROTATE WITH NON-HOST CROP."
        }
    },
    {
        "page_number": 5,
        "id": "disease_3",
        "content": {
            "disease_name": "BACTERIAL SPOT",
            "causative_agent": "Xanthomonas euvesicatoria, Xanthomonas vesicatoria, Xanthomonas perforans, Xanthomonas gardneri",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) FOLIAR SYMPTOMS APPEAR AS DARK, WATER-SOAKED, CIRCULAR SPOTS LESS THAN 3 MILLIMETERS IN DIAMETER. 2) ON SEEDLINGS, INFECTIONS MAY CAUSE SEVERE DEFOLIATION. 3) SPOTS BECOME ANGULAR AND THE SURFACES MAY APPEAR GREASY, WITH TRANSLUCENT CENTERS AND BLACK MARGINS. 4) LARGER LEAF BLOTCHES MAY ALSO OCCUR. 5) THE CENTERS OF THESE LESIONS SOON DRY AND CRACK, AND YELLOW HALOS MAY SURROUND THE LESIONS. 6) DURING PERIODS OF HIGH MOISTURE LEAVES WILL TURN CHLOROTIC AND BECOME BLIGHTED. 7) DISEASE CAN DEVELOP ON ALL ABOVE-GROUND PARTS OF THE PLANT. 8) FRUIT INFECTION BEGINS AS SMALL, BLACK, RAISED SPOTS WHICH MAY BE SURROUNDED BY A WHITE, GREASY-APPEARING HALO. 9) FRUIT LESIONS TYPICALLY ENLARGE TO 4-5 MM IN DIAMETER AND CAN BE DARK-BROWN WITH RAISED MARGINS AND SUNKEN, TAN CENTERS. 10) FRUIT LESIONS OFTEN APPEAR SCAB-LIKE OR CORKY.",
            "conditions_for_the_disease": "1) BACTERIA CAN SURVIVE IN CROP DEBRIS, ON VOLUNTEER PLANTS, WEEDS AND SEED. 2) THE BACTERIUM IS SEED BORNE. 3) OVERHEAD IRRIGATION CAN RESULT IN RAPID SPREAD. 4) IN THE FIELD, INFECTION GENERALLY OCCURS THROUGH WOUNDS. 5) SECONDARY SPREAD OCCURS BY SPLASHING WATER FROM SPRINKLER IRRIGATION OR RAIN. 6) WARM TEMPERATURES (24-30°C) COMBINED WITH HEAVY RAINS OR SPRINKLER IRRIGATION FAVOR DISEASE DEVELOPMENT.",
            "cure__control_and_management": "1) USE PATHOGEN-FREE SEED AND DISEASE-FREE TRANSPLANTS. 2) AVOID SPRINKLER IRRIGATION AND CULL PILES NEAR GREENHOUSE OR FIELD, AND ROTATE WITH A NON-HOST CROP. 3) COPPER SPRAYS CAN PROVIDE MODERATE LEVELS OF PROTECTION. 4) AVOID OVERHEAD IRRIGATION. 5) ROTATE TO NON-HOST CROPS AND CONTROL WEEDS AND VOLUNTEER PLANTS. 6) GOOD SANITATION PRACTICES AND PLOWING UNDER DEBRIS IMMEDIATELY AFTER HARVEST CAN REDUCE LOSSES."
        }
    },
    {
        "page_number": 6,
        "id": "disease_4",
        "content": {
            "disease_name": "BACTERIAL WILT",
            "causative_agent": "Ralstonia pseudosolanacearum, Ralstonia solanacearum, Ralstonia syzygii subsp. indonesiensis",
            "distribution": "Ralstonia pseudosolanacearum: Africa, Asia. Ralstonia solanacearum: Caribbean, Central America, North America. Ralstonia syzygii subsp. indonesiensis: Indonesia",
            "signs_and_symptoms": "1) ONSET BEGINS WITH DROOPING OF LOWER LEAVES FOLLOWED SOON AFTER BY WILTING OF ENTIRE PLANTS. 2) THE FIRST SYMPTOM IS WILTING OF A FEW LEAVES. 3) ENTIRE PLANT WILTS SUDDENLY AND DIES. 4) DRAMATIC SYMPTOMS OCCUR WHEN WEATHER IS HOT (86-95 F) AND SOIL MOISTURE IS PLENTIFUL. 5) UNDER LESS CONDUCIVE CONDITIONS, DECLINE IS SLOWER, ADVENTITIOUS ROOTS FORM ON LOWER STEMS. 6) NO FOLIAR YELLOWING IS ASSOCIATED WITH THIS WILT DISEASE. 7) LONGITUDINAL SECTION OF STEM REVEALS YELLOW TO LIGHT-BROWN VASCULAR DISCOLORATION. 8) DIAGNOSTIC METHOD: PLACE A FRESHLY CUT STEM IN A GLASS OF WATER; A WHITE, MILKY STREAM OF BACTERIA WILL OOZE. 9) MATURE, FRUIT-BEARING PLANTS ARE AFFECTED IN MID-SUMMER. 10) ROOTS EXHIBIT VARYING DEGREES OF DECAY.",
            "conditions_for_the_disease": "1) HOST RANGE OF MORE THAN 200 PLANT SPECIES. 2) PATHOGENS SURVIVE IN SOIL WHERE THEY INFECT ROOTS THROUGH NATURAL WOUNDS OR WOUNDS FROM TRANSPLANTING, CULTIVATION OR NEMATODES. 3) CHEWING INSECTS MAY TRANSMIT. 4) SPREAD BY RAIN WATER, SURFACE IRRIGATION, CONTAMINATED EQUIPMENT, AND DISEASED TRANSPLANTS. 5) WARM (29-35°C) OR HOT (36-40°C) WEATHER AND HIGH SOIL MOISTURE FAVOR DEVELOPMENT. 6) PLANT-TO-PLANT SPREAD VIA ROOTS. 7) NON-AIRBORNE PATHOGEN.",
            "cure__control_and_management": "1) AVOID LAND WITH A HISTORY OF BACTERIAL WILT. 2) ENSURE TRANSPLANTS ARE DISEASE-FREE AND GROW HYBRID VARIETIES WITH RESISTANCE OR GRAFT ONTO RESISTANT ROOTSTOCKS. 3) SOIL FUMIGATION OR SOLARIZATION, AND COVER-CROPPING OR CROP ROTATION TO A NON-HOST SPECIES CAN REDUCE INCIDENCE."
        }
    },
    {
        "page_number": 8,
        "id": "disease_5",
        "content": {
            "disease_name": "EARLY BLIGHT",
            "causative_agent": "Alternaria tomatophila, Alternaria solani",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) SYMPTOMS APPEAR FIRST ON OLDER LEAVES AS IRREGULAR, DARK-BROWN, NECROTIC LESIONS. 2) LESIONS EXPAND AND DEVELOP CONCENTRIC, BLACK RINGS (TARGET-BOARD APPEARANCE). 3) A CHLOROTIC AREA OFTEN SURROUNDS LEAF LESIONS. 4) IF NUMEROUS LESIONS, ENTIRE LEAF WILL TURN YELLOW AND SENESCE. 5) COMPLETE DEFOLIATION CAN OCCUR. 6) LESIONS APPEAR AS DARK-BROWN, ELONGATED, SUNKEN AREAS ON STEMS AND PETIOLES. 7) COLLAR ROT MAY GIRDLE STEMS AT SOIL LINE. 8) FRUIT LESIONS OCCUR AT THE CALYX END AND ARE DARK, LEATHERY AND SUNKEN. 9) STEMS AND PETIOLES AFFECTED HAVE ELLIPTICAL CONCENTRIC LESIONS WHICH WEAKEN THE PLANT.",
            "conditions_for_the_disease": "1) FAVOURED BY WARM TEMPERATURES (24-29°C) AND EXTENDED PERIODS OF LEAF WETNESS. 2) DISEASE CYCLE IS ABOUT FIVE TO SEVEN DAYS. 3) SURVIVES FROM SEASON TO SEASON ON PLANT DEBRIS IN SOIL. 4) VOLUNTEER TOMATOES, POTATOES AND SOLANACEOUS WEEDS SERVE AS INOCULUM. 5) CONIDIA DISSEMINATED BY WIND AND RAIN. 6) PLANTS UNDER STRESS ARE MORE SUSCEPTIBLE. 7) PREVALENT ON OLD TRANSPLANTS OR STRESSED TRANSPLANTS.",
            "cure__control_and_management": "1) FUNGICIDE SPRAY PROGRAM COMBINED WITH FORECASTING SYSTEM. 2) FIELD SANITATION: CROP ROTATION, WEED CONTROL, REMOVE DEBRIS. 3) MINIMIZE PLANT INJURY; AVOID SANDY SOILS. 4) TRELLIS VINES AND AVOID DENSE PLANT POPULATIONS FOR VENTILATION. 5) USE FURROW OR DRIP IRRIGATION. 6) REMOVE OR DESTROY DISEASED PLANTS IMMEDIATELY AFTER HARVEST."
        }
    },
    {
        "page_number": 9,
        "id": "disease_6",
        "content": {
            "disease_name": "FUSARIUM WILT",
            "causative_agent": "Fusarium oxysporum f. sp. lycopersici (Three races have been described)",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) INFECTED SEEDLINGS ARE STUNTED AND THE OLDEST LEAVES TURN YELLOW AND WILT. 2) SEVERELY INFECTED SEEDLINGS FREQUENTLY DIE. 3) DEGREE OF STUNTING DEPENDS UPON TIME OF ROOT INFECTION. 4) ON OLDER PLANTS, SYMPTOMS BEGIN WITH YELLOWING OF THE OLDEST LEAVES AT FRUIT SET. 5) YELLOWING ON ONLY ONE SIDE OF A LEAF OR BRANCH. 6) INFECTED LEAVES SHOW DOWNWARD CURLING, BROWNING AND DRYING. 7) ENTIRE BRANCHES TURN YELLOW PRODUCING A 'YELLOW FLAG' APPEARANCE. 8) AFFECTED LEAVES WILT AND DIE BUT REMAIN ATTACHED. 9) DIURNAL WILTING DURING SUNNY DAYS. 10) RED-BROWN DISCOLORATION OF VASCULAR TISSUE. 11) VASCULAR DISCOLORATION MAY EXTEND THROUGHOUT MAIN STEM.",
            "conditions_for_the_disease": "1) SOIL BORNE AND PERSISTS FOR MANY YEARS IN SOIL WITHOUT HOST. 2) MOST INFECTIONS ORIGINATE FROM FUNGUS ASSOCIATED WITH TOMATO DEBRIS. 3) ROOT-KNOT NEMATODE INFECTION MAKES RESISTANT VARIETIES MORE SUSCEPTIBLE. 4) FAVOURED BY WARM TEMPERATURES (27-28 °C), DRY WEATHER, AND ACIDIC SOIL (PH 5-5.6). 5) RAPIDLY GROWING SUCCULENT PLANTS EXPOSED TO AMMONIUM NITRATE ARE SUSCEPTIBLE. 6) ENHANCED BY HIGH LEVELS OF MICRONUTRIENTS, PHOSPHOROUS AND AMMONIA NITROGEN.",
            "cure__control_and_management": "1) USE RESISTANT VARIETIES. 2) DISINFECT EQUIPMENT BEFORE MOVING TO CLEAN FIELDS. 3) RAISE SOIL PH TO 6.5-7.0 AND USE NITRATE NITROGEN SOURCES. 4) CULTIVATE CROPS ONLY WHEN NECESSARY TO AVOID ROOT DAMAGE. 5) CONTROL ROOT-KNOT NEMATODES. 6) APPLY BIO CONTROL AGENTS LIKE TRICHODERMA VIRIDAE."
        }
    },
    {
        "page_number": 10,
        "id": "disease_7",
        "content": {
            "disease_name": "LATE BLIGHT",
            "causative_agent": "Phytophthora infestans",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) FIRST SYMPTOM IS A BENDING DOWN OF PETIOLES. 2) LEAF AND STEM LESIONS MANIFEST AS LARGE (2-10 MM), IRREGULAR, GREENISH, WATER-SOAKED PATCHES. 3) PURPLISH TINGE ON UPPER LEAF SURFACE. 4) ALL ABOVEGROUND PARTS MAY SHOW SYMPTOMS. 5) PATCHES ENLARGE AND TURN BROWN AND PAPER-LIKE. 6) DURING WET WEATHER, FUNGUS GROWS AND SPORULATES FROM LESIONS ON ABAXIAL LEAF SURFACES. 7) RAPID BLIGHTING OF FOLIAGE DURING MOIST PERIODS. 8) FRUIT LESIONS MANIFEST AS LARGE, FIRM, IRREGULAR, BROWNISH-GREEN BLOTCHES. 9) FRUIT LESIONS ARE ROUGH AND GREASY. 10) DOWNY WHITE MOLD APPEARS NEAR LEAF SPOT MARGINS UNDER HUMID CONDITIONS. 11) INVASION OF FRUIT OFTEN BEGINS AT STEM END. 12) LESIONS HAVE AN OLIVE-BROWN APPEARANCE WITH ROUGH LEATHERY SURFACE.",
            "conditions_for_the_disease": "1) COMMON IN TROPICAL HIGHLANDS AND TEMPERATE REGIONS. 2) REQUIRES EXTENDED LEAF WETNESS AND COOL TO MODERATE TEMPERATURES (13-20 °C) AND WET WEATHER. 3) HOT, DRY WEATHER STOPS DISEASE. 4) SPORES SPREAD BY WIND AND SPLASHING RAIN. 5) SURVIVES ON VOLUNTEER TOMATOES/POTATOES, CULL PILES, AND SOLANACEOUS WEEDS. 6) REQUIRES HIGH HUMIDITY TO INFECT.",
            "cure__control_and_management": "1) IMPLEMENT FORECASTING SYSTEM AND SPRAY PROGRAM. 2) AVOID PLANTING NEAR POTATO FIELDS. 3) MAINTAIN LOWER HUMIDITY IN PROTECTED CULTURE. 4) REDUCE LEAF WETNESS BY STAKING AND DRIP IRRIGATION. 5) USE SPRINKLER IRRIGATION IN MORNING/MIDDAY TO PREVENT WET FOLIAGE OVERNIGHT. 6) AVOID OVER FERTILIZATION OF NITROGEN. 7) USE LESS SUSCEPTIBLE VARIETIES."
        }
    },
    {
        "page_number": 11,
        "id": "disease_8",
        "content": {
            "disease_name": "LEAF MOLD",
            "causative_agent": "Passalora fulva (synonym = Fulvia fulva; Cladosporium fulvum) Five races have been described",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) USUALLY INFECTS LEAVES; STEMS, BLOSSOMS, AND FRUIT MAY ALSO BE INFECTED. 2) SYMPTOMS FIRST APPEAR AS LIGHT-GREEN TO YELLOWISH AREAS ON ADAXIAL SURFACE OF OLDER LEAVES. 3) YELLOW SPOTS APPEAR ON UPPER SURFACE, OLIVE-GREEN TO BROWN SPORE MASSES APPEAR ON LOWER SURFACE. 4) MASSES OF OLIVE-GREEN CONIDIA DEVELOP ON ABAXIAL SURFACE. 5) LOWER LEAVES TURN YELLOW, NECROTIC, FOLLOWED BY DRYING AND DEFOLIATION. 6) UNRIPE FRUIT MAY OCCASIONALLY DEVELOP DARK LEATHERY LESIONS. 7) BLACK LEATHERY ROT MAY DEVELOP ON CALYX END.",
            "conditions_for_the_disease": "1) TOMATO IS THE ONLY CROP AFFECTED. 2) SURVIVES AS CONIDIA AND SCLEROTIA IN SOIL AND PLANT DEBRIS FOR AT LEAST ONE YEAR. 3) REQUIRES HIGH RELATIVE HUMIDITY (GREATER THAN 90%). 4) WARM TEMPERATURES (22-24 °C) ARE REQUIRED. 5) LEAF MOLD WILL NOT DEVELOP IF RH IS LESS THAN 85%. 6) MORE SEVERE DURING COOLER PERIODS IN TROPICS. 7) COMMON DURING SUMMER/AUTUMN IN GREENHOUSES. 8) SPORES DISSEMINATED BY AIR CURRENTS, WATER, WORKERS, INSECTS. 9) SPREAD ON WORKERS' CLOTHING AND EQUIPMENT.",
            "cure__control_and_management": "1) REDUCE PLANT DENSITIES TO IMPROVE AIR CIRCULATION. 2) REDUCE HIGH RATES OF NITROGEN FERTILIZATION. 3) IMPLEMENT FUNGICIDE SPRAY PROGRAM. 4) REMOVE AND DESTROY INFECTED CROP RESIDUES. 5) AVOID PLANTING NEW TOMATO PLANTS NEAR DISEASED PLANTS. 6) REDUCES HIGHER LEVELS OF DISEASE EARLY ON. 7) GROW RESISTANT VARIETIES IF POSSIBLE."
        }
    },
    {
        "page_number": 12,
        "id": "disease_9",
        "content": {
            "disease_name": "SEPTORIA LEAF SPOT",
            "causative_agent": "Septoria lycopersici",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) SYMPTOMS FIRST APPEAR AS SMALL, DARK, WATER-SOAKED SPOTS ON OLDER LEAVES. 2) ENLARGE TO FORM CIRCULAR LESIONS ABOUT 5 MM IN DIAMETER. 3) CENTERS GRADUALLY TURN GRAY TO TAN WITH DARK BROWN MARGINS. 4) SPOTS ARE DISTINCTIVELY CIRCULAR AND NUMEROUS. 5) LESIONS HAVE BORDERS WITH GRAY CENTERS PEPPERED WITH SMALL, BLACK PYCNIDIA. 6) LESIONS ON STEMS/PETIOLES TEND TO BE ELONGATED. 7) LESIONS COALESCE, LEAVES COLLAPSE AND PLANTS DEFOLIATE. 8) DIAGNOSTIC FEATURE: PRESENCE OF MANY DARK BROWN, PIMPLE-LIKE STRUCTURES (PYCNIDIA) VISIBLE IN THE TAN CENTERS.",
            "conditions_for_the_disease": "1) FAVOURED BY WARM, WET, HUMID CONDITIONS. 2) MAIN SOURCE OF INOCULUM IS LEAF FRAGMENTS AND DEBRIS OVERWINTERING IN SOIL. 3) SPORES PRODUCED IN PYCNIDIA UNDER WET CONDITIONS. 4) REQUIRES EXTENDED PERIODS OF 100% RELATIVE HUMIDITY AND 20-25°C. 5) SPORE PRODUCTION ABUNDANT AT 60°-80°F. 6) SPORES EXUDED WHEN HUMIDITY IS HIGH. 7) SPREAD BY WINDBLOWN WATER, SPLASHING RAIN, OVERHEAD IRRIGATION. 8) SPREAD CAN OCCUR VIA HANDS, EQUIPMENT, INSECTS.",
            "cure__control_and_management": "1) ESTABLISH A FUNGICIDE SPRAY PROGRAM. 2) TURN UNDER OR REMOVE PLANT DEBRIS. 3) DEEP PLOUGHING IN LARGE FIELDS. 4) ROTATE TO NON-HOST CROP FOR THREE YEARS. 5) ROTATE WITH NON-SOLANACEOUS CROPS. 6) AVOID OVERHEAD WATERING; WATER EARLY IN THE DAY. 7) AVOID WORKING WITH WET PLANTS. 8) STAKING AND MULCHING HELPS REDUCE INFECTIONS. 9) STAKING INCREASES AIR CIRCULATION."
        }
    },
    {
        "page_number": 13,
        "id": "disease_10",
        "content": {
            "disease_name": "TARGET SPOT",
            "causative_agent": "Corynespora cassiicola",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) ALL ABOVE-GROUND PARTS CAN BE INFECTED. 2) BEGINS AS TINY LESIONS THAT ENLARGE INTO LIGHT-BROWN LESIONS WITH DISTINCT YELLOW HALOS. 3) INCREASE IN SIZE (UP TO 2 CM), BECOMING CIRCULAR, FREQUENTLY RINGED. 4) LESIONS GROW TOGETHER CAUSING TISSUE COLLAPSE. 5) STEM LESIONS RAPIDLY ENLARGE AND MAY GIRDLE STEMS, CAUSING FOLIAGE COLLAPSE. 6) EXTENSIVE TISSUE COLLAPSE AND EVENTUALLY PLANT DEATH. 7) IMMATURE FRUIT INFECTION BEGINS AS MINUTE, DARK-BROWN, SUNKEN SPOTS. 8) LARGE, BROWN, CIRCULAR LESIONS WITH CRACKED CENTERS DEVELOP ON MATURE FRUIT. 9) FUNGAL SPORULATION COMMONLY OCCURS FROM LESIONS.",
            "conditions_for_the_disease": "1) BROAD HOST RANGE. 2) ATTACKS TOMATO, PEPPER, TOBACCO, SOYBEAN, ETC. 3) INFECTION OCCURS BETWEEN 16 AND 32°C DURING LONG PERIODS (>16 HOURS) OF HIGH MOISTURE. 4) CONIDIA SPREAD BY AIR MOVEMENT AND RAINFALL. 5) FUNGUS SPORULATES ABUNDANTLY ON RAIN-MOISTENED DEBRIS. 6) CAN COLONIZE WEEDS/OTHER CROPS. 7) REMAINS VIABLE FOR UP TO TWO YEARS. 8) READILY DISPERSED BY WIND/RAIN. 9) SPLASHING SOIL CREATES WOUNDS FOR SPORES TO ENTER FRUIT.",
            "cure__control_and_management": "1) INITIATE FUNGICIDE SPRAY PROGRAM PRIOR TO SYMPTOMS. 2) REMOVE AFFECTED DEBRIS. 3) USE ADEQUATE PERIOD OF CROP ROTATION. 4) GENETIC RESISTANCE DOCUMENTED BUT COMMERCIAL VARIETIES NOT YET AVAILABLE."
        }
    },
    {
        "page_number": 15,
        "id": "disease_11",
        "content": {
            "disease_name": "TOMATO MOSAIC",
            "causative_agent": "Tomato mosaic virus (ToMV)",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) SYMPTOMS FOUND AT ANY GROWTH STAGE; ALL PLANT PARTS AFFECTED. 2) LIGHT OR DARK GREEN MOTTLING OR MOSAIC WITH DISTORTION OF YOUNGER LEAVES, AND STUNTING. 3) SEVERELY AFFECTED LEAVES MAY HAVE A 'FERNLIKE' APPEARANCE. 4) FRUIT SET SEVERELY REDUCED. 5) INTERNAL BROWNING OF FRUIT WALL; YELLOW BLOTCHES/NECROTIC SPOTS ON FRUIT. 6) SOME STRAINS CAUSE YELLOW MOTTLING, DARK NECROTIC STREAKS. 7) SYMPTOMS INFLUENCED BY ENVIRONMENTAL CONDITIONS (DAY LENGTH, TEMP, LIGHT), AGE, STRAIN VIRULENCE. 8) DUAL INFECTION WITH POTATO VIRUS X CAUSES 'DOUBLE STREAK'. 9) SOME SYMPTOMS RESEMBLE 2,4-D HORMONE DAMAGE.",
            "conditions_for_the_disease": "1) VIRUS IS SEED-BORNE. 2) INFESTED SEEDS CAN DISSEMINATE VIRUS OVER LARGE DISTANCES. 3) SPREAD BY WORKERS ON HANDS, CLOTHING, TOOLS. 4) VERY STABLE: PERSISTS IN DEBRIS IN DRY SOIL FOR 2 YEARS, MOIST SOIL FOR 1 MONTH. 5) INFECTION THROUGH MINOR ROOT WOUNDS IN CONTAMINATED SOIL. 6) MAY BE PRESENT IN IRRIGATION WATER. 7) DISSEMINATION BY WINDBLOWN CONTAMINATED SOIL.",
            "cure__control_and_management": "1) USE SEED FROM HEALTHY PLANTS. 2) DRY HEATING SEED AT 70°C FOR 4 DAYS OR 82-85°C FOR 24 HR TO ELIMINATE SURFACE VIRUS. 3) SOAK SEED IN TSP SOLUTION FOR 15 MIN. 4) USE MINIMUM 2-YEAR ROTATION. 5) AVOID FOLLOWING TOMATO CROPS WITH SUSCEPTIBLE CROPS. 6) DIP HANDS IN MILK WHILE HANDLING PLANTS. 7) REMOVE DISEASED PLANTS AS SOON AS NOTICED. 8) DISINFECT TOOLS, STAKES, EQUIPMENT (HEAT OR CHEMICAL DILUTIONS). 9) WORK IN DISEASED AREAS LAST. 10) WASH CLOTHING IN HOT WATER AND DETERGENT."
        }
    },
    {
        "page_number": 16,
        "id": "disease_12",
        "content": {
            "disease_name": "TOMATO YELLOW LEAF CURL",
            "causative_agent": "Tomato Yellow Leaf Curl Virus (TYLCV)",
            "distribution": "WORLDWIDE",
            "signs_and_symptoms": "1) PLANTS SEVERELY STUNTED WITH ERECT SHOOTS. 2) LEAFLETS REDUCED IN SIZE AND PUCKER. 3) LEAFLETS CURL UPWARDS, DISTORTED, PROMINENT YELLOWING ALONG MARGINS/INTERVEINAL REGIONS. 4) FLOWERS WITHER. 5) VERY FEW FRUITS SET IF INFECTED EARLY, LEADING TO EXTREMELY LOW YIELDS. 6) APPEARANCE OF THE FRUIT IS UNAFFECTED.",
            "conditions_for_the_disease": "1) VIRUS IS NOT SEED-BORNE. 2) TRANSMITTED ONLY BY WHITEFLY (BEMISIA TABACI). 3) WHITEFLY ACQUIRES VIRUS AFTER FEEDING 15-30 MINS. 4) TRANSMITS AFTER 24 HOURS INCUBATION. 5) REQUIRES 15 MINS FEEDING ON NEW HOST FOR TRANSMISSION. 6) WHITEFLY RETAINS VIRUS UP TO 20 DAYS (NOT TRANSMITTED TO PROGENY). 7) SYMPTOMS DEVELOP AFTER 10-14 DAYS. 8) HOT/DRY CONDITIONS FAVOUR WHITEFLY SPREAD. 9) POPULATIONS DECREASE AFTER HEAVY RAINS. 10) PASSIVELY WIND-DRIVEN OVER LONG DISTANCES. 11) DISEASE INCIDENCE INCREASES RAPIDLY (UP TO 100% AT HARVEST). 12) INCIDENCE VARIES WITH LOCATION. 13) TOBACCO IS SYMPTOMLESS HOST AND SOURCE OF RE-INFECTION. 14) WEEDS LIKE JIMSONWEED SERVE AS INOCULUM.",
            "cure__control_and_management": "1) GROW SEEDLINGS IN INSECT-PROOF NET HOUSE/GREENHOUSE. 2) PLANT NEW CROPS IN ISOLATED FIELDS. 3) PLANT TALL BORDER CROP (E.G., MAIZE). 4) USE UV-REFLECTIVE OR YELLOW MULCHES TO REDUCE WHITEFLY LANDING. 5) 1% SOAP SOLUTION TO LEAF UNDER-SURFACE TO CONTROL ADULTS. 6) OIL SPRAYS MAY BE EFFECTIVE. 7) NEEM TREE SEED EXTRACTS CONTROL NYMPHS/ADULTS. 8) TYLCV-RESISTANT/TOLERANT VARIETIES AVAILABLE. 9) SYSTEMIC INSECTICIDES (LIKE CONFIDOR) AS SOIL DRENCH/SPRAY. 10) SECOND APPLICATION MAY BE NECESSARY."
        }
    }
]

with open("tomato_data_clean.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=4)

print("✅ FULL Data saved as 'tomato_data_clean.json'")